title: Crafteo Formation
subtitle: "Formation DevOps & Cloud"
email: pierre@crafteo.io
description: >-
  Formation DevOps & Cloud par la pratique
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  PierreBeucher

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  # - jekyll-paginate
  # - jekyll-sitemap
  # - jekyll-gist
  # - jemoji
  # - jekyll-include-cache

include:
  - _pages

exclude:
- Taskfile.yml
- Dockerfile
- .dockerignore
- docker-compose.yml

minimal_mistakes_skin    : "neon" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

search: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
